//
//  RDStyleKit.m
//  RaceData
//
//  Created by Alaija on 01/02/16.
//  Copyright (c) 2016 RaceData. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "RDStyleKit.h"


@implementation RDStyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawDayModeSpeedometerWithFrame2: (CGRect)frame2 fillColor: (UIColor*)fillColor pressure: (CGFloat)pressure
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Variable Declarations
    CGFloat angle = -274 * pressure;

    //// Bezier Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.17543 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.92645 * CGRectGetHeight(frame2));

    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(-9.55, 9.66)];
    [bezierPath addLineToPoint: CGPointMake(9.55, -9.66)];
    [fillColor setStroke];
    bezierPath.lineWidth = 1;
    [bezierPath stroke];

    CGContextRestoreGState(context);


    //// Bezier 2 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.12387 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.86920 * CGRectGetHeight(frame2));

    UIBezierPath* bezier2Path = [UIBezierPath bezierPath];
    [bezier2Path moveToPoint: CGPointMake(-9.7, 6.83)];
    [bezier2Path addLineToPoint: CGPointMake(9.7, -6.83)];
    [fillColor setStroke];
    bezier2Path.lineWidth = 1;
    [bezier2Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 3 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.08852 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.78655 * CGRectGetHeight(frame2));

    UIBezierPath* bezier3Path = [UIBezierPath bezierPath];
    [bezier3Path moveToPoint: CGPointMake(-10.57, 5.11)];
    [bezier3Path addLineToPoint: CGPointMake(10.57, -5.11)];
    [fillColor setStroke];
    bezier3Path.lineWidth = 1;
    [bezier3Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 4 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.04821 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.70659 * CGRectGetHeight(frame2));

    UIBezierPath* bezier4Path = [UIBezierPath bezierPath];
    [bezier4Path moveToPoint: CGPointMake(-11.28, 3.24)];
    [bezier4Path addLineToPoint: CGPointMake(11.28, -3.24)];
    [fillColor setStroke];
    bezier4Path.lineWidth = 1;
    [bezier4Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 5 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.03929 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.61773 * CGRectGetHeight(frame2));

    UIBezierPath* bezier5Path = [UIBezierPath bezierPath];
    [bezier5Path moveToPoint: CGPointMake(-11.67, 1.28)];
    [bezier5Path addLineToPoint: CGPointMake(11.67, -1.28)];
    [fillColor setStroke];
    bezier5Path.lineWidth = 1;
    [bezier5Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 6 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.03414 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.53049 * CGRectGetHeight(frame2));

    UIBezierPath* bezier6Path = [UIBezierPath bezierPath];
    [bezier6Path moveToPoint: CGPointMake(-11.71, -0.72)];
    [bezier6Path addLineToPoint: CGPointMake(11.71, 0.72)];
    [fillColor setStroke];
    bezier6Path.lineWidth = 1;
    [bezier6Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 7 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.05159 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.44814 * CGRectGetHeight(frame2));

    UIBezierPath* bezier7Path = [UIBezierPath bezierPath];
    [bezier7Path moveToPoint: CGPointMake(-11.42, -2.7)];
    [bezier7Path addLineToPoint: CGPointMake(11.42, 2.7)];
    [fillColor setStroke];
    bezier7Path.lineWidth = 1;
    [bezier7Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 8 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.07246 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.35929 * CGRectGetHeight(frame2));

    UIBezierPath* bezier8Path = [UIBezierPath bezierPath];
    [bezier8Path moveToPoint: CGPointMake(-10.8, -4.6)];
    [bezier8Path addLineToPoint: CGPointMake(10.8, 4.6)];
    [fillColor setStroke];
    bezier8Path.lineWidth = 1;
    [bezier8Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 9 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.11152 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.28529 * CGRectGetHeight(frame2));

    UIBezierPath* bezier9Path = [UIBezierPath bezierPath];
    [bezier9Path moveToPoint: CGPointMake(-9.87, -6.37)];
    [bezier9Path addLineToPoint: CGPointMake(9.87, 6.37)];
    [fillColor setStroke];
    bezier9Path.lineWidth = 1;
    [bezier9Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 10 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.16119 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.21442 * CGRectGetHeight(frame2));

    UIBezierPath* bezier10Path = [UIBezierPath bezierPath];
    [bezier10Path moveToPoint: CGPointMake(-8.65, -7.96)];
    [bezier10Path addLineToPoint: CGPointMake(8.65, 7.96)];
    [fillColor setStroke];
    bezier10Path.lineWidth = 1;
    [bezier10Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 11 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.22290 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.15655 * CGRectGetHeight(frame2));

    UIBezierPath* bezier11Path = [UIBezierPath bezierPath];
    [bezier11Path moveToPoint: CGPointMake(-7.18, -9.31)];
    [bezier11Path addLineToPoint: CGPointMake(7.18, 9.31)];
    [fillColor setStroke];
    bezier11Path.lineWidth = 1;
    [bezier11Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 12 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.28521 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.09928 * CGRectGetHeight(frame2));

    UIBezierPath* bezier12Path = [UIBezierPath bezierPath];
    [bezier12Path moveToPoint: CGPointMake(-5.5, -10.4)];
    [bezier12Path addLineToPoint: CGPointMake(5.5, 10.4)];
    [fillColor setStroke];
    bezier12Path.lineWidth = 1;
    [bezier12Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 13 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.35516 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.07357 * CGRectGetHeight(frame2));

    UIBezierPath* bezier13Path = [UIBezierPath bezierPath];
    [bezier13Path moveToPoint: CGPointMake(-3.67, -11.18)];
    [bezier13Path addLineToPoint: CGPointMake(3.67, 11.18)];
    [fillColor setStroke];
    bezier13Path.lineWidth = 1;
    [bezier13Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 14 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.43331 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.04786 * CGRectGetHeight(frame2));

    UIBezierPath* bezier14Path = [UIBezierPath bezierPath];
    [bezier14Path moveToPoint: CGPointMake(-1.72, -11.64)];
    [bezier14Path addLineToPoint: CGPointMake(1.73, 11.64)];
    [fillColor setStroke];
    bezier14Path.lineWidth = 1;
    [bezier14Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 15 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.51070 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.04477 * CGRectGetHeight(frame2));

    UIBezierPath* bezier15Path = [UIBezierPath bezierPath];
    [bezier15Path moveToPoint: CGPointMake(0.27, -11.77)];
    [bezier15Path addLineToPoint: CGPointMake(-0.27, 11.77)];
    [fillColor setStroke];
    bezier15Path.lineWidth = 1;
    [bezier15Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 16 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.59081 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.05355 * CGRectGetHeight(frame2));

    UIBezierPath* bezier16Path = [UIBezierPath bezierPath];
    [bezier16Path moveToPoint: CGPointMake(2.25, -11.55)];
    [bezier16Path addLineToPoint: CGPointMake(-2.25, 11.55)];
    [fillColor setStroke];
    bezier16Path.lineWidth = 1;
    [bezier16Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 17 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.66773 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.07749 * CGRectGetHeight(frame2));

    UIBezierPath* bezier17Path = [UIBezierPath bezierPath];
    [bezier17Path moveToPoint: CGPointMake(4.17, -11)];
    [bezier17Path addLineToPoint: CGPointMake(-4.17, 11)];
    [fillColor setStroke];
    bezier17Path.lineWidth = 1;
    [bezier17Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 18 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.73254 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.11569 * CGRectGetHeight(frame2));

    UIBezierPath* bezier18Path = [UIBezierPath bezierPath];
    [bezier18Path moveToPoint: CGPointMake(5.97, -10.13)];
    [bezier18Path addLineToPoint: CGPointMake(-5.97, 10.13)];
    [fillColor setStroke];
    bezier18Path.lineWidth = 1;
    [bezier18Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 19 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.80149 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.17039 * CGRectGetHeight(frame2));

    UIBezierPath* bezier19Path = [UIBezierPath bezierPath];
    [bezier19Path moveToPoint: CGPointMake(7.59, -8.98)];
    [bezier19Path addLineToPoint: CGPointMake(-7.59, 8.98)];
    [fillColor setStroke];
    bezier19Path.lineWidth = 1;
    [bezier19Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 20 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.85357 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.23237 * CGRectGetHeight(frame2));

    UIBezierPath* bezier20Path = [UIBezierPath bezierPath];
    [bezier20Path moveToPoint: CGPointMake(9, -7.56)];
    [bezier20Path addLineToPoint: CGPointMake(-9, 7.56)];
    [fillColor setStroke];
    bezier20Path.lineWidth = 1;
    [bezier20Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 21 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.89932 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.30298 * CGRectGetHeight(frame2));

    UIBezierPath* bezier21Path = [UIBezierPath bezierPath];
    [bezier21Path moveToPoint: CGPointMake(10.14, -5.92)];
    [bezier21Path addLineToPoint: CGPointMake(-10.14, 5.92)];
    [fillColor setStroke];
    bezier21Path.lineWidth = 1;
    [bezier21Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 22 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.93401 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.38684 * CGRectGetHeight(frame2));

    UIBezierPath* bezier22Path = [UIBezierPath bezierPath];
    [bezier22Path moveToPoint: CGPointMake(11, -4.11)];
    [bezier22Path addLineToPoint: CGPointMake(-11, 4.11)];
    [fillColor setStroke];
    bezier22Path.lineWidth = 1;
    [bezier22Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 23 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.95959 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.47369 * CGRectGetHeight(frame2));

    UIBezierPath* bezier23Path = [UIBezierPath bezierPath];
    [bezier23Path moveToPoint: CGPointMake(11.53, -2.18)];
    [bezier23Path addLineToPoint: CGPointMake(-11.53, 2.18)];
    [fillColor setStroke];
    bezier23Path.lineWidth = 1;
    [bezier23Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 24 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.96596 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.55310 * CGRectGetHeight(frame2));

    UIBezierPath* bezier24Path = [UIBezierPath bezierPath];
    [bezier24Path moveToPoint: CGPointMake(11.73, -0.19)];
    [bezier24Path addLineToPoint: CGPointMake(-11.73, 0.19)];
    [fillColor setStroke];
    bezier24Path.lineWidth = 1;
    [bezier24Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 25 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.95907 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.64372 * CGRectGetHeight(frame2));

    UIBezierPath* bezier25Path = [UIBezierPath bezierPath];
    [bezier25Path moveToPoint: CGPointMake(11.6, 1.81)];
    [bezier25Path addLineToPoint: CGPointMake(-11.6, -1.81)];
    [fillColor setStroke];
    bezier25Path.lineWidth = 1;
    [bezier25Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 26 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.93601 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.73500 * CGRectGetHeight(frame2));

    UIBezierPath* bezier26Path = [UIBezierPath bezierPath];
    [bezier26Path moveToPoint: CGPointMake(11.12, 3.75)];
    [bezier26Path addLineToPoint: CGPointMake(-11.12, -3.75)];
    [fillColor setStroke];
    bezier26Path.lineWidth = 1;
    [bezier26Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 27 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.90370 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.81646 * CGRectGetHeight(frame2));

    UIBezierPath* bezier27Path = [UIBezierPath bezierPath];
    [bezier27Path moveToPoint: CGPointMake(10.33, 5.58)];
    [bezier27Path addLineToPoint: CGPointMake(-10.33, -5.58)];
    [fillColor setStroke];
    bezier27Path.lineWidth = 1;
    [bezier27Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 28 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.86324 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.88878 * CGRectGetHeight(frame2));

    UIBezierPath* bezier28Path = [UIBezierPath bezierPath];
    [bezier28Path moveToPoint: CGPointMake(9.24, 7.26)];
    [bezier28Path addLineToPoint: CGPointMake(-9.24, -7.26)];
    [fillColor setStroke];
    bezier28Path.lineWidth = 1;
    [bezier28Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 29 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.80679 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.95654 * CGRectGetHeight(frame2));

    UIBezierPath* bezier29Path = [UIBezierPath bezierPath];
    [bezier29Path moveToPoint: CGPointMake(7.88, 8.72)];
    [bezier29Path addLineToPoint: CGPointMake(-7.88, -8.72)];
    [fillColor setStroke];
    bezier29Path.lineWidth = 1;
    [bezier29Path stroke];

    CGContextRestoreGState(context);


    //// Bezier 39 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.23453 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.84682 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier39Path = [UIBezierPath bezierPath];
    [bezier39Path moveToPoint: CGPointMake(2.4, -6.32)];
    [bezier39Path addCurveToPoint: CGPointMake(0, -8.56) controlPoint1: CGPointMake(2.4, -7.86) controlPoint2: CGPointMake(1.42, -8.56)];
    [bezier39Path addCurveToPoint: CGPointMake(-2.4, -6.32) controlPoint1: CGPointMake(-1.42, -8.56) controlPoint2: CGPointMake(-2.4, -7.86)];
    [bezier39Path addLineToPoint: CGPointMake(-2.4, 6.32)];
    [bezier39Path addCurveToPoint: CGPointMake(0, 8.57) controlPoint1: CGPointMake(-2.4, 7.86) controlPoint2: CGPointMake(-1.42, 8.57)];
    [bezier39Path addCurveToPoint: CGPointMake(2.4, 6.32) controlPoint1: CGPointMake(1.42, 8.57) controlPoint2: CGPointMake(2.4, 7.86)];
    [bezier39Path addLineToPoint: CGPointMake(2.4, -6.32)];
    [bezier39Path closePath];
    [bezier39Path moveToPoint: CGPointMake(0, 11.18)];
    [bezier39Path addCurveToPoint: CGPointMake(-6.22, 6.46) controlPoint1: CGPointMake(-3.82, 11.18) controlPoint2: CGPointMake(-6.22, 9.44)];
    [bezier39Path addLineToPoint: CGPointMake(-6.22, -6.46)];
    [bezier39Path addCurveToPoint: CGPointMake(0, -11.18) controlPoint1: CGPointMake(-6.22, -9.43) controlPoint2: CGPointMake(-3.82, -11.18)];
    [bezier39Path addCurveToPoint: CGPointMake(6.22, -6.46) controlPoint1: CGPointMake(3.83, -11.18) controlPoint2: CGPointMake(6.22, -9.43)];
    [bezier39Path addLineToPoint: CGPointMake(6.22, 6.46)];
    [bezier39Path addCurveToPoint: CGPointMake(0, 11.18) controlPoint1: CGPointMake(6.22, 9.44) controlPoint2: CGPointMake(3.83, 11.18)];
    [bezier39Path closePath];
    [fillColor setFill];
    [bezier39Path fill];

    CGContextRestoreGState(context);


    //// Bezier 40 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.12750 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.58940 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier40Path = [UIBezierPath bezierPath];
    [bezier40Path moveToPoint: CGPointMake(-5.96, 11.04)];
    [bezier40Path addLineToPoint: CGPointMake(-5.96, 6.46)];
    [bezier40Path addCurveToPoint: CGPointMake(-1.69, 0.77) controlPoint1: CGPointMake(-5.96, 3.92) controlPoint2: CGPointMake(-4, 2.24)];
    [bezier40Path addCurveToPoint: CGPointMake(1.91, -3.45) controlPoint1: CGPointMake(0.67, -0.77) controlPoint2: CGPointMake(1.91, -1.81)];
    [bezier40Path addLineToPoint: CGPointMake(1.91, -6.19)];
    [bezier40Path addCurveToPoint: CGPointMake(-0.18, -8.43) controlPoint1: CGPointMake(1.91, -7.73) controlPoint2: CGPointMake(1.16, -8.43)];
    [bezier40Path addCurveToPoint: CGPointMake(-2.22, -6.19) controlPoint1: CGPointMake(-1.56, -8.43) controlPoint2: CGPointMake(-2.22, -7.73)];
    [bezier40Path addLineToPoint: CGPointMake(-2.22, -3.88)];
    [bezier40Path addLineToPoint: CGPointMake(-6, -3.88)];
    [bezier40Path addLineToPoint: CGPointMake(-6, -6.32)];
    [bezier40Path addCurveToPoint: CGPointMake(-0.18, -11.04) controlPoint1: CGPointMake(-6, -9.3) controlPoint2: CGPointMake(-3.91, -11.04)];
    [bezier40Path addCurveToPoint: CGPointMake(5.74, -6.32) controlPoint1: CGPointMake(3.56, -11.04) controlPoint2: CGPointMake(5.74, -9.3)];
    [bezier40Path addLineToPoint: CGPointMake(5.74, -3.31)];
    [bezier40Path addCurveToPoint: CGPointMake(1.38, 2.38) controlPoint1: CGPointMake(5.74, -0.77) controlPoint2: CGPointMake(3.69, 0.9)];
    [bezier40Path addCurveToPoint: CGPointMake(-2.18, 6.59) controlPoint1: CGPointMake(-0.98, 3.92) controlPoint2: CGPointMake(-2.18, 4.95)];
    [bezier40Path addLineToPoint: CGPointMake(-2.18, 8.43)];
    [bezier40Path addLineToPoint: CGPointMake(6, 8.43)];
    [bezier40Path addLineToPoint: CGPointMake(6, 11.04)];
    [bezier40Path addLineToPoint: CGPointMake(-5.96, 11.04)];
    [bezier40Path closePath];
    [fillColor setFill];
    [bezier40Path fill];

    CGContextRestoreGState(context);


    //// Bezier 41 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.15836 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.58989 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier41Path = [UIBezierPath bezierPath];
    [bezier41Path moveToPoint: CGPointMake(2.4, -6.32)];
    [bezier41Path addCurveToPoint: CGPointMake(0, -8.56) controlPoint1: CGPointMake(2.4, -7.86) controlPoint2: CGPointMake(1.42, -8.56)];
    [bezier41Path addCurveToPoint: CGPointMake(-2.4, -6.32) controlPoint1: CGPointMake(-1.42, -8.56) controlPoint2: CGPointMake(-2.4, -7.86)];
    [bezier41Path addLineToPoint: CGPointMake(-2.4, 6.32)];
    [bezier41Path addCurveToPoint: CGPointMake(0, 8.57) controlPoint1: CGPointMake(-2.4, 7.86) controlPoint2: CGPointMake(-1.42, 8.57)];
    [bezier41Path addCurveToPoint: CGPointMake(2.4, 6.32) controlPoint1: CGPointMake(1.42, 8.57) controlPoint2: CGPointMake(2.4, 7.86)];
    [bezier41Path addLineToPoint: CGPointMake(2.4, -6.32)];
    [bezier41Path closePath];
    [bezier41Path moveToPoint: CGPointMake(0, 11.18)];
    [bezier41Path addCurveToPoint: CGPointMake(-6.22, 6.46) controlPoint1: CGPointMake(-3.82, 11.18) controlPoint2: CGPointMake(-6.22, 9.44)];
    [bezier41Path addLineToPoint: CGPointMake(-6.22, -6.46)];
    [bezier41Path addCurveToPoint: CGPointMake(0, -11.18) controlPoint1: CGPointMake(-6.22, -9.43) controlPoint2: CGPointMake(-3.82, -11.18)];
    [bezier41Path addCurveToPoint: CGPointMake(6.22, -6.46) controlPoint1: CGPointMake(3.83, -11.18) controlPoint2: CGPointMake(6.22, -9.43)];
    [bezier41Path addLineToPoint: CGPointMake(6.22, 6.46)];
    [bezier41Path addCurveToPoint: CGPointMake(0, 11.18) controlPoint1: CGPointMake(6.22, 9.44) controlPoint2: CGPointMake(3.83, 11.18)];
    [bezier41Path closePath];
    [fillColor setFill];
    [bezier41Path fill];

    CGContextRestoreGState(context);


    //// Bezier 42 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.16082 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.31527 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier42Path = [UIBezierPath bezierPath];
    [bezier42Path moveToPoint: CGPointMake(3.73, 15.35)];
    [bezier42Path addLineToPoint: CGPointMake(8.35, 15.35)];
    [bezier42Path addLineToPoint: CGPointMake(8.35, 6.95)];
    [bezier42Path addCurveToPoint: CGPointMake(8.89, 2.92) controlPoint1: CGPointMake(8.35, 4.94) controlPoint2: CGPointMake(8.89, 2.92)];
    [bezier42Path addLineToPoint: CGPointMake(3.73, 15.35)];
    [bezier42Path closePath];
    [bezier42Path moveToPoint: CGPointMake(12.21, 17.83)];
    [bezier42Path addLineToPoint: CGPointMake(12.21, 21.89)];
    [bezier42Path addLineToPoint: CGPointMake(8.35, 21.89)];
    [bezier42Path addLineToPoint: CGPointMake(8.35, 17.83)];
    [bezier42Path addLineToPoint: CGPointMake(0, 17.83)];
    [bezier42Path addLineToPoint: CGPointMake(0, 15.58)];
    [bezier42Path addLineToPoint: CGPointMake(7.27, 0)];
    [bezier42Path addLineToPoint: CGPointMake(12.21, 0)];
    [bezier42Path addLineToPoint: CGPointMake(12.21, 15.35)];
    [bezier42Path addLineToPoint: CGPointMake(14.5, 15.35)];
    [bezier42Path addLineToPoint: CGPointMake(14.5, 17.83)];
    [bezier42Path addLineToPoint: CGPointMake(12.21, 17.83)];
    [bezier42Path closePath];
    [fillColor setFill];
    [bezier42Path fill];

    CGContextRestoreGState(context);


    //// Bezier 43 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.19477 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.31429 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier43Path = [UIBezierPath bezierPath];
    [bezier43Path moveToPoint: CGPointMake(8.71, 4.87)];
    [bezier43Path addCurveToPoint: CGPointMake(6.28, 2.62) controlPoint1: CGPointMake(8.71, 3.32) controlPoint2: CGPointMake(7.72, 2.62)];
    [bezier43Path addCurveToPoint: CGPointMake(3.86, 4.87) controlPoint1: CGPointMake(4.85, 2.62) controlPoint2: CGPointMake(3.86, 3.32)];
    [bezier43Path addLineToPoint: CGPointMake(3.86, 17.56)];
    [bezier43Path addCurveToPoint: CGPointMake(6.28, 19.81) controlPoint1: CGPointMake(3.86, 19.11) controlPoint2: CGPointMake(4.85, 19.81)];
    [bezier43Path addCurveToPoint: CGPointMake(8.71, 17.56) controlPoint1: CGPointMake(7.72, 19.81) controlPoint2: CGPointMake(8.71, 19.11)];
    [bezier43Path addLineToPoint: CGPointMake(8.71, 4.87)];
    [bezier43Path closePath];
    [bezier43Path moveToPoint: CGPointMake(6.28, 22.43)];
    [bezier43Path addCurveToPoint: CGPointMake(0, 17.7) controlPoint1: CGPointMake(2.42, 22.43) controlPoint2: CGPointMake(0, 20.69)];
    [bezier43Path addLineToPoint: CGPointMake(0, 4.74)];
    [bezier43Path addCurveToPoint: CGPointMake(6.28, 0) controlPoint1: CGPointMake(0, 1.75) controlPoint2: CGPointMake(2.42, 0)];
    [bezier43Path addCurveToPoint: CGPointMake(12.57, 4.74) controlPoint1: CGPointMake(10.15, 0) controlPoint2: CGPointMake(12.57, 1.75)];
    [bezier43Path addLineToPoint: CGPointMake(12.57, 17.7)];
    [bezier43Path addCurveToPoint: CGPointMake(6.28, 22.43) controlPoint1: CGPointMake(12.57, 20.69) controlPoint2: CGPointMake(10.15, 22.43)];
    [bezier43Path closePath];
    [fillColor setFill];
    [bezier43Path fill];

    CGContextRestoreGState(context);


    //// Bezier 44 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.34555 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.14664 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier44Path = [UIBezierPath bezierPath];
    [bezier44Path moveToPoint: CGPointMake(8.53, 13.6)];
    [bezier44Path addCurveToPoint: CGPointMake(6.2, 11.32) controlPoint1: CGPointMake(8.53, 12.06) controlPoint2: CGPointMake(7.63, 11.32)];
    [bezier44Path addCurveToPoint: CGPointMake(3.86, 13.6) controlPoint1: CGPointMake(4.76, 11.32) controlPoint2: CGPointMake(3.86, 12.06)];
    [bezier44Path addLineToPoint: CGPointMake(3.86, 17.56)];
    [bezier44Path addCurveToPoint: CGPointMake(6.2, 19.81) controlPoint1: CGPointMake(3.86, 19.11) controlPoint2: CGPointMake(4.76, 19.81)];
    [bezier44Path addCurveToPoint: CGPointMake(8.53, 17.56) controlPoint1: CGPointMake(7.63, 19.81) controlPoint2: CGPointMake(8.53, 19.11)];
    [bezier44Path addLineToPoint: CGPointMake(8.53, 13.6)];
    [bezier44Path closePath];
    [bezier44Path moveToPoint: CGPointMake(6.2, 22.43)];
    [bezier44Path addCurveToPoint: CGPointMake(0, 17.7) controlPoint1: CGPointMake(2.33, 22.43) controlPoint2: CGPointMake(0, 20.69)];
    [bezier44Path addLineToPoint: CGPointMake(0, 4.74)];
    [bezier44Path addCurveToPoint: CGPointMake(6.15, 0) controlPoint1: CGPointMake(0, 1.75) controlPoint2: CGPointMake(2.29, 0)];
    [bezier44Path addCurveToPoint: CGPointMake(12.25, 4.74) controlPoint1: CGPointMake(10.01, 0) controlPoint2: CGPointMake(12.25, 1.75)];
    [bezier44Path addLineToPoint: CGPointMake(12.25, 7.19)];
    [bezier44Path addLineToPoint: CGPointMake(8.44, 7.19)];
    [bezier44Path addLineToPoint: CGPointMake(8.44, 4.87)];
    [bezier44Path addCurveToPoint: CGPointMake(6.15, 2.62) controlPoint1: CGPointMake(8.44, 3.32) controlPoint2: CGPointMake(7.59, 2.62)];
    [bezier44Path addCurveToPoint: CGPointMake(3.86, 4.87) controlPoint1: CGPointMake(4.71, 2.62) controlPoint2: CGPointMake(3.86, 3.32)];
    [bezier44Path addLineToPoint: CGPointMake(3.86, 10.07)];
    [bezier44Path addCurveToPoint: CGPointMake(7.05, 8.73) controlPoint1: CGPointMake(4.26, 9.3) controlPoint2: CGPointMake(5.75, 8.73)];
    [bezier44Path addCurveToPoint: CGPointMake(12.39, 13.47) controlPoint1: CGPointMake(10.68, 8.73) controlPoint2: CGPointMake(12.39, 10.44)];
    [bezier44Path addLineToPoint: CGPointMake(12.39, 17.7)];
    [bezier44Path addCurveToPoint: CGPointMake(6.2, 22.43) controlPoint1: CGPointMake(12.39, 20.69) controlPoint2: CGPointMake(10.05, 22.43)];
    [bezier44Path closePath];
    [fillColor setFill];
    [bezier44Path fill];

    CGContextRestoreGState(context);


    //// Bezier 45 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.37878 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.14664 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier45Path = [UIBezierPath bezierPath];
    [bezier45Path moveToPoint: CGPointMake(8.71, 4.87)];
    [bezier45Path addCurveToPoint: CGPointMake(6.28, 2.62) controlPoint1: CGPointMake(8.71, 3.32) controlPoint2: CGPointMake(7.72, 2.62)];
    [bezier45Path addCurveToPoint: CGPointMake(3.86, 4.87) controlPoint1: CGPointMake(4.85, 2.62) controlPoint2: CGPointMake(3.86, 3.32)];
    [bezier45Path addLineToPoint: CGPointMake(3.86, 17.56)];
    [bezier45Path addCurveToPoint: CGPointMake(6.28, 19.81) controlPoint1: CGPointMake(3.86, 19.11) controlPoint2: CGPointMake(4.85, 19.81)];
    [bezier45Path addCurveToPoint: CGPointMake(8.71, 17.56) controlPoint1: CGPointMake(7.72, 19.81) controlPoint2: CGPointMake(8.71, 19.11)];
    [bezier45Path addLineToPoint: CGPointMake(8.71, 4.87)];
    [bezier45Path closePath];
    [bezier45Path moveToPoint: CGPointMake(6.28, 22.43)];
    [bezier45Path addCurveToPoint: CGPointMake(0, 17.7) controlPoint1: CGPointMake(2.42, 22.43) controlPoint2: CGPointMake(0, 20.69)];
    [bezier45Path addLineToPoint: CGPointMake(0, 4.74)];
    [bezier45Path addCurveToPoint: CGPointMake(6.28, 0) controlPoint1: CGPointMake(0, 1.75) controlPoint2: CGPointMake(2.42, 0)];
    [bezier45Path addCurveToPoint: CGPointMake(12.57, 4.74) controlPoint1: CGPointMake(10.15, 0) controlPoint2: CGPointMake(12.57, 1.75)];
    [bezier45Path addLineToPoint: CGPointMake(12.57, 17.7)];
    [bezier45Path addCurveToPoint: CGPointMake(6.28, 22.43) controlPoint1: CGPointMake(12.57, 20.69) controlPoint2: CGPointMake(10.15, 22.43)];
    [bezier45Path closePath];
    [fillColor setFill];
    [bezier45Path fill];

    CGContextRestoreGState(context);


    //// Bezier 46 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.60462 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.14664 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier46Path = [UIBezierPath bezierPath];
    [bezier46Path moveToPoint: CGPointMake(8.98, 4.87)];
    [bezier46Path addCurveToPoint: CGPointMake(6.51, 2.62) controlPoint1: CGPointMake(8.98, 3.32) controlPoint2: CGPointMake(7.95, 2.62)];
    [bezier46Path addCurveToPoint: CGPointMake(4.04, 4.87) controlPoint1: CGPointMake(5.07, 2.62) controlPoint2: CGPointMake(4.04, 3.32)];
    [bezier46Path addLineToPoint: CGPointMake(4.04, 7.66)];
    [bezier46Path addCurveToPoint: CGPointMake(6.51, 9.91) controlPoint1: CGPointMake(4.04, 9.2) controlPoint2: CGPointMake(5.07, 9.91)];
    [bezier46Path addCurveToPoint: CGPointMake(8.98, 7.66) controlPoint1: CGPointMake(7.95, 9.91) controlPoint2: CGPointMake(8.98, 9.2)];
    [bezier46Path addLineToPoint: CGPointMake(8.98, 4.87)];
    [bezier46Path closePath];
    [bezier46Path moveToPoint: CGPointMake(9.16, 14.31)];
    [bezier46Path addCurveToPoint: CGPointMake(6.51, 12.06) controlPoint1: CGPointMake(9.16, 12.76) controlPoint2: CGPointMake(7.95, 12.06)];
    [bezier46Path addCurveToPoint: CGPointMake(3.86, 14.31) controlPoint1: CGPointMake(5.07, 12.06) controlPoint2: CGPointMake(3.86, 12.76)];
    [bezier46Path addLineToPoint: CGPointMake(3.86, 17.56)];
    [bezier46Path addCurveToPoint: CGPointMake(6.51, 19.81) controlPoint1: CGPointMake(3.86, 19.11) controlPoint2: CGPointMake(5.07, 19.81)];
    [bezier46Path addCurveToPoint: CGPointMake(9.16, 17.56) controlPoint1: CGPointMake(7.95, 19.81) controlPoint2: CGPointMake(9.16, 19.11)];
    [bezier46Path addLineToPoint: CGPointMake(9.16, 14.31)];
    [bezier46Path closePath];
    [bezier46Path moveToPoint: CGPointMake(6.51, 22.43)];
    [bezier46Path addCurveToPoint: CGPointMake(0, 17.7) controlPoint1: CGPointMake(2.56, 22.43) controlPoint2: CGPointMake(0, 20.75)];
    [bezier46Path addLineToPoint: CGPointMake(0, 14.44)];
    [bezier46Path addCurveToPoint: CGPointMake(2.6, 10.81) controlPoint1: CGPointMake(0, 12.76) controlPoint2: CGPointMake(0.99, 11.32)];
    [bezier46Path addCurveToPoint: CGPointMake(0.18, 7.52) controlPoint1: CGPointMake(1.26, 10.21) controlPoint2: CGPointMake(0.18, 8.97)];
    [bezier46Path addLineToPoint: CGPointMake(0.18, 4.74)];
    [bezier46Path addCurveToPoint: CGPointMake(6.51, 0) controlPoint1: CGPointMake(0.18, 1.75) controlPoint2: CGPointMake(2.65, 0)];
    [bezier46Path addCurveToPoint: CGPointMake(12.84, 4.74) controlPoint1: CGPointMake(10.37, 0) controlPoint2: CGPointMake(12.84, 1.75)];
    [bezier46Path addLineToPoint: CGPointMake(12.84, 7.52)];
    [bezier46Path addCurveToPoint: CGPointMake(10.41, 10.81) controlPoint1: CGPointMake(12.84, 8.97) controlPoint2: CGPointMake(11.76, 10.21)];
    [bezier46Path addCurveToPoint: CGPointMake(13.02, 14.44) controlPoint1: CGPointMake(12.03, 11.32) controlPoint2: CGPointMake(13.02, 12.76)];
    [bezier46Path addLineToPoint: CGPointMake(13.02, 17.7)];
    [bezier46Path addCurveToPoint: CGPointMake(6.51, 22.43) controlPoint1: CGPointMake(13.02, 20.79) controlPoint2: CGPointMake(10.5, 22.43)];
    [bezier46Path closePath];
    [fillColor setFill];
    [bezier46Path fill];

    CGContextRestoreGState(context);


    //// Bezier 47 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.63892 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.14664 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier47Path = [UIBezierPath bezierPath];
    [bezier47Path moveToPoint: CGPointMake(8.71, 4.87)];
    [bezier47Path addCurveToPoint: CGPointMake(6.28, 2.62) controlPoint1: CGPointMake(8.71, 3.32) controlPoint2: CGPointMake(7.72, 2.62)];
    [bezier47Path addCurveToPoint: CGPointMake(3.86, 4.87) controlPoint1: CGPointMake(4.85, 2.62) controlPoint2: CGPointMake(3.86, 3.32)];
    [bezier47Path addLineToPoint: CGPointMake(3.86, 17.56)];
    [bezier47Path addCurveToPoint: CGPointMake(6.28, 19.81) controlPoint1: CGPointMake(3.86, 19.11) controlPoint2: CGPointMake(4.85, 19.81)];
    [bezier47Path addCurveToPoint: CGPointMake(8.71, 17.56) controlPoint1: CGPointMake(7.72, 19.81) controlPoint2: CGPointMake(8.71, 19.11)];
    [bezier47Path addLineToPoint: CGPointMake(8.71, 4.87)];
    [bezier47Path closePath];
    [bezier47Path moveToPoint: CGPointMake(6.28, 22.43)];
    [bezier47Path addCurveToPoint: CGPointMake(0, 17.7) controlPoint1: CGPointMake(2.42, 22.43) controlPoint2: CGPointMake(0, 20.69)];
    [bezier47Path addLineToPoint: CGPointMake(0, 4.74)];
    [bezier47Path addCurveToPoint: CGPointMake(6.28, 0) controlPoint1: CGPointMake(0, 1.75) controlPoint2: CGPointMake(2.42, 0)];
    [bezier47Path addCurveToPoint: CGPointMake(12.57, 4.74) controlPoint1: CGPointMake(10.15, 0) controlPoint2: CGPointMake(12.57, 1.75)];
    [bezier47Path addLineToPoint: CGPointMake(12.57, 17.7)];
    [bezier47Path addCurveToPoint: CGPointMake(6.28, 22.43) controlPoint1: CGPointMake(12.57, 20.69) controlPoint2: CGPointMake(10.15, 22.43)];
    [bezier47Path closePath];
    [fillColor setFill];
    [bezier47Path fill];

    CGContextRestoreGState(context);


    //// Bezier 48 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.71376 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.84682 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier48Path = [UIBezierPath bezierPath];
    [bezier48Path moveToPoint: CGPointMake(-0.27, 10.91)];
    [bezier48Path addLineToPoint: CGPointMake(-0.27, -6.29)];
    [bezier48Path addLineToPoint: CGPointMake(-3.6, -6.29)];
    [bezier48Path addLineToPoint: CGPointMake(-3.6, -8.46)];
    [bezier48Path addCurveToPoint: CGPointMake(0.36, -10.91) controlPoint1: CGPointMake(-1.65, -8.57) controlPoint2: CGPointMake(0.13, -9.2)];
    [bezier48Path addLineToPoint: CGPointMake(3.6, -10.91)];
    [bezier48Path addLineToPoint: CGPointMake(3.6, 10.91)];
    [bezier48Path addLineToPoint: CGPointMake(-0.27, 10.91)];
    [bezier48Path closePath];
    [fillColor setFill];
    [bezier48Path fill];

    CGContextRestoreGState(context);


    //// Bezier 49 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.74594 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.84682 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier49Path = [UIBezierPath bezierPath];
    [bezier49Path moveToPoint: CGPointMake(-3.49, 4.38)];
    [bezier49Path addLineToPoint: CGPointMake(1.09, 4.38)];
    [bezier49Path addLineToPoint: CGPointMake(1.09, -3.98)];
    [bezier49Path addCurveToPoint: CGPointMake(1.62, -8) controlPoint1: CGPointMake(1.09, -5.99) controlPoint2: CGPointMake(1.62, -8)];
    [bezier49Path addLineToPoint: CGPointMake(-3.49, 4.38)];
    [bezier49Path closePath];
    [bezier49Path moveToPoint: CGPointMake(4.91, 6.86)];
    [bezier49Path addLineToPoint: CGPointMake(4.91, 10.91)];
    [bezier49Path addLineToPoint: CGPointMake(1.09, 10.91)];
    [bezier49Path addLineToPoint: CGPointMake(1.09, 6.86)];
    [bezier49Path addLineToPoint: CGPointMake(-7.18, 6.86)];
    [bezier49Path addLineToPoint: CGPointMake(-7.18, 4.62)];
    [bezier49Path addLineToPoint: CGPointMake(0.02, -10.91)];
    [bezier49Path addLineToPoint: CGPointMake(4.91, -10.91)];
    [bezier49Path addLineToPoint: CGPointMake(4.91, 4.38)];
    [bezier49Path addLineToPoint: CGPointMake(7.18, 4.38)];
    [bezier49Path addLineToPoint: CGPointMake(7.18, 6.86)];
    [bezier49Path addLineToPoint: CGPointMake(4.91, 6.86)];
    [bezier49Path closePath];
    [fillColor setFill];
    [bezier49Path fill];

    CGContextRestoreGState(context);


    //// Bezier 50 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.78590 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.84682 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier50Path = [UIBezierPath bezierPath];
    [bezier50Path moveToPoint: CGPointMake(2.4, -6.32)];
    [bezier50Path addCurveToPoint: CGPointMake(0, -8.56) controlPoint1: CGPointMake(2.4, -7.86) controlPoint2: CGPointMake(1.42, -8.56)];
    [bezier50Path addCurveToPoint: CGPointMake(-2.4, -6.32) controlPoint1: CGPointMake(-1.42, -8.56) controlPoint2: CGPointMake(-2.4, -7.86)];
    [bezier50Path addLineToPoint: CGPointMake(-2.4, 6.32)];
    [bezier50Path addCurveToPoint: CGPointMake(0, 8.57) controlPoint1: CGPointMake(-2.4, 7.86) controlPoint2: CGPointMake(-1.42, 8.57)];
    [bezier50Path addCurveToPoint: CGPointMake(2.4, 6.32) controlPoint1: CGPointMake(1.42, 8.57) controlPoint2: CGPointMake(2.4, 7.86)];
    [bezier50Path addLineToPoint: CGPointMake(2.4, -6.32)];
    [bezier50Path closePath];
    [bezier50Path moveToPoint: CGPointMake(0, 11.18)];
    [bezier50Path addCurveToPoint: CGPointMake(-6.22, 6.46) controlPoint1: CGPointMake(-3.82, 11.18) controlPoint2: CGPointMake(-6.22, 9.44)];
    [bezier50Path addLineToPoint: CGPointMake(-6.22, -6.46)];
    [bezier50Path addCurveToPoint: CGPointMake(0, -11.18) controlPoint1: CGPointMake(-6.22, -9.43) controlPoint2: CGPointMake(-3.82, -11.18)];
    [bezier50Path addCurveToPoint: CGPointMake(6.22, -6.46) controlPoint1: CGPointMake(3.82, -11.18) controlPoint2: CGPointMake(6.22, -9.43)];
    [bezier50Path addLineToPoint: CGPointMake(6.22, 6.46)];
    [bezier50Path addCurveToPoint: CGPointMake(0, 11.18) controlPoint1: CGPointMake(6.22, 9.44) controlPoint2: CGPointMake(3.82, 11.18)];
    [bezier50Path closePath];
    [fillColor setFill];
    [bezier50Path fill];

    CGContextRestoreGState(context);


    //// Bezier 51 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.81259 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.63668 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier51Path = [UIBezierPath bezierPath];
    [bezier51Path moveToPoint: CGPointMake(-0.27, 10.91)];
    [bezier51Path addLineToPoint: CGPointMake(-0.27, -6.29)];
    [bezier51Path addLineToPoint: CGPointMake(-3.6, -6.29)];
    [bezier51Path addLineToPoint: CGPointMake(-3.6, -8.47)];
    [bezier51Path addCurveToPoint: CGPointMake(0.36, -10.91) controlPoint1: CGPointMake(-1.65, -8.57) controlPoint2: CGPointMake(0.13, -9.2)];
    [bezier51Path addLineToPoint: CGPointMake(3.6, -10.91)];
    [bezier51Path addLineToPoint: CGPointMake(3.6, 10.91)];
    [bezier51Path addLineToPoint: CGPointMake(-0.27, 10.91)];
    [bezier51Path closePath];
    [fillColor setFill];
    [bezier51Path fill];

    CGContextRestoreGState(context);


    //// Bezier 52 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.84330 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.63619 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier52Path = [UIBezierPath bezierPath];
    [bezier52Path moveToPoint: CGPointMake(-5.96, 11.04)];
    [bezier52Path addLineToPoint: CGPointMake(-5.96, 6.46)];
    [bezier52Path addCurveToPoint: CGPointMake(-1.69, 0.77) controlPoint1: CGPointMake(-5.96, 3.92) controlPoint2: CGPointMake(-4, 2.24)];
    [bezier52Path addCurveToPoint: CGPointMake(1.91, -3.45) controlPoint1: CGPointMake(0.67, -0.77) controlPoint2: CGPointMake(1.91, -1.81)];
    [bezier52Path addLineToPoint: CGPointMake(1.91, -6.19)];
    [bezier52Path addCurveToPoint: CGPointMake(-0.18, -8.43) controlPoint1: CGPointMake(1.91, -7.73) controlPoint2: CGPointMake(1.16, -8.43)];
    [bezier52Path addCurveToPoint: CGPointMake(-2.22, -6.19) controlPoint1: CGPointMake(-1.56, -8.43) controlPoint2: CGPointMake(-2.22, -7.73)];
    [bezier52Path addLineToPoint: CGPointMake(-2.22, -3.88)];
    [bezier52Path addLineToPoint: CGPointMake(-6, -3.88)];
    [bezier52Path addLineToPoint: CGPointMake(-6, -6.32)];
    [bezier52Path addCurveToPoint: CGPointMake(-0.18, -11.04) controlPoint1: CGPointMake(-6, -9.3) controlPoint2: CGPointMake(-3.91, -11.04)];
    [bezier52Path addCurveToPoint: CGPointMake(5.74, -6.32) controlPoint1: CGPointMake(3.56, -11.04) controlPoint2: CGPointMake(5.74, -9.3)];
    [bezier52Path addLineToPoint: CGPointMake(5.74, -3.31)];
    [bezier52Path addCurveToPoint: CGPointMake(1.38, 2.38) controlPoint1: CGPointMake(5.74, -0.77) controlPoint2: CGPointMake(3.69, 0.9)];
    [bezier52Path addCurveToPoint: CGPointMake(-2.18, 6.59) controlPoint1: CGPointMake(-0.98, 3.92) controlPoint2: CGPointMake(-2.18, 4.95)];
    [bezier52Path addLineToPoint: CGPointMake(-2.18, 8.43)];
    [bezier52Path addLineToPoint: CGPointMake(6, 8.43)];
    [bezier52Path addLineToPoint: CGPointMake(6, 11.04)];
    [bezier52Path addLineToPoint: CGPointMake(-5.96, 11.04)];
    [bezier52Path closePath];
    [fillColor setFill];
    [bezier52Path fill];

    CGContextRestoreGState(context);


    //// Bezier 53 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.87729 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.63668 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier53Path = [UIBezierPath bezierPath];
    [bezier53Path moveToPoint: CGPointMake(2.4, -6.32)];
    [bezier53Path addCurveToPoint: CGPointMake(0, -8.57) controlPoint1: CGPointMake(2.4, -7.86) controlPoint2: CGPointMake(1.42, -8.57)];
    [bezier53Path addCurveToPoint: CGPointMake(-2.4, -6.32) controlPoint1: CGPointMake(-1.42, -8.57) controlPoint2: CGPointMake(-2.4, -7.86)];
    [bezier53Path addLineToPoint: CGPointMake(-2.4, 6.32)];
    [bezier53Path addCurveToPoint: CGPointMake(0, 8.57) controlPoint1: CGPointMake(-2.4, 7.86) controlPoint2: CGPointMake(-1.42, 8.57)];
    [bezier53Path addCurveToPoint: CGPointMake(2.4, 6.32) controlPoint1: CGPointMake(1.42, 8.57) controlPoint2: CGPointMake(2.4, 7.86)];
    [bezier53Path addLineToPoint: CGPointMake(2.4, -6.32)];
    [bezier53Path closePath];
    [bezier53Path moveToPoint: CGPointMake(0, 11.18)];
    [bezier53Path addCurveToPoint: CGPointMake(-6.22, 6.46) controlPoint1: CGPointMake(-3.82, 11.18) controlPoint2: CGPointMake(-6.22, 9.44)];
    [bezier53Path addLineToPoint: CGPointMake(-6.22, -6.46)];
    [bezier53Path addCurveToPoint: CGPointMake(0, -11.18) controlPoint1: CGPointMake(-6.22, -9.44) controlPoint2: CGPointMake(-3.82, -11.18)];
    [bezier53Path addCurveToPoint: CGPointMake(6.22, -6.46) controlPoint1: CGPointMake(3.82, -11.18) controlPoint2: CGPointMake(6.22, -9.44)];
    [bezier53Path addLineToPoint: CGPointMake(6.22, 6.46)];
    [bezier53Path addCurveToPoint: CGPointMake(0, 11.18) controlPoint1: CGPointMake(6.22, 9.44) controlPoint2: CGPointMake(3.82, 11.18)];
    [bezier53Path closePath];
    [fillColor setFill];
    [bezier53Path fill];

    CGContextRestoreGState(context);


    //// Bezier 54 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.79697 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.35797 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier54Path = [UIBezierPath bezierPath];
    [bezier54Path moveToPoint: CGPointMake(-0.27, 10.91)];
    [bezier54Path addLineToPoint: CGPointMake(-0.27, -6.29)];
    [bezier54Path addLineToPoint: CGPointMake(-3.6, -6.29)];
    [bezier54Path addLineToPoint: CGPointMake(-3.6, -8.47)];
    [bezier54Path addCurveToPoint: CGPointMake(0.36, -10.91) controlPoint1: CGPointMake(-1.64, -8.56) controlPoint2: CGPointMake(0.13, -9.2)];
    [bezier54Path addLineToPoint: CGPointMake(3.6, -10.91)];
    [bezier54Path addLineToPoint: CGPointMake(3.6, 10.91)];
    [bezier54Path addLineToPoint: CGPointMake(-0.27, 10.91)];
    [bezier54Path closePath];
    [fillColor setFill];
    [bezier54Path fill];

    CGContextRestoreGState(context);


    //// Bezier 55 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.82664 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.35797 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier55Path = [UIBezierPath bezierPath];
    [bezier55Path moveToPoint: CGPointMake(2.4, -6.32)];
    [bezier55Path addCurveToPoint: CGPointMake(0, -8.57) controlPoint1: CGPointMake(2.4, -7.86) controlPoint2: CGPointMake(1.42, -8.57)];
    [bezier55Path addCurveToPoint: CGPointMake(-2.4, -6.32) controlPoint1: CGPointMake(-1.42, -8.57) controlPoint2: CGPointMake(-2.4, -7.86)];
    [bezier55Path addLineToPoint: CGPointMake(-2.4, 6.32)];
    [bezier55Path addCurveToPoint: CGPointMake(0, 8.57) controlPoint1: CGPointMake(-2.4, 7.86) controlPoint2: CGPointMake(-1.42, 8.57)];
    [bezier55Path addCurveToPoint: CGPointMake(2.4, 6.32) controlPoint1: CGPointMake(1.42, 8.57) controlPoint2: CGPointMake(2.4, 7.86)];
    [bezier55Path addLineToPoint: CGPointMake(2.4, -6.32)];
    [bezier55Path closePath];
    [bezier55Path moveToPoint: CGPointMake(0, 11.18)];
    [bezier55Path addCurveToPoint: CGPointMake(-6.23, 6.46) controlPoint1: CGPointMake(-3.82, 11.18) controlPoint2: CGPointMake(-6.23, 9.44)];
    [bezier55Path addLineToPoint: CGPointMake(-6.23, -6.46)];
    [bezier55Path addCurveToPoint: CGPointMake(0, -11.18) controlPoint1: CGPointMake(-6.23, -9.44) controlPoint2: CGPointMake(-3.82, -11.18)];
    [bezier55Path addCurveToPoint: CGPointMake(6.23, -6.46) controlPoint1: CGPointMake(3.83, -11.18) controlPoint2: CGPointMake(6.23, -9.44)];
    [bezier55Path addLineToPoint: CGPointMake(6.23, 6.46)];
    [bezier55Path addCurveToPoint: CGPointMake(0, 11.18) controlPoint1: CGPointMake(6.23, 9.44) controlPoint2: CGPointMake(3.83, 11.18)];
    [bezier55Path closePath];
    [fillColor setFill];
    [bezier55Path fill];

    CGContextRestoreGState(context);


    //// Bezier 56 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.86001 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.35797 * CGRectGetHeight(frame2));
    CGContextScaleCTM(context, 0.7, 1);

    UIBezierPath* bezier56Path = [UIBezierPath bezierPath];
    [bezier56Path moveToPoint: CGPointMake(2.4, -6.32)];
    [bezier56Path addCurveToPoint: CGPointMake(0, -8.57) controlPoint1: CGPointMake(2.4, -7.86) controlPoint2: CGPointMake(1.42, -8.57)];
    [bezier56Path addCurveToPoint: CGPointMake(-2.4, -6.32) controlPoint1: CGPointMake(-1.42, -8.57) controlPoint2: CGPointMake(-2.4, -7.86)];
    [bezier56Path addLineToPoint: CGPointMake(-2.4, 6.32)];
    [bezier56Path addCurveToPoint: CGPointMake(0, 8.57) controlPoint1: CGPointMake(-2.4, 7.86) controlPoint2: CGPointMake(-1.42, 8.57)];
    [bezier56Path addCurveToPoint: CGPointMake(2.4, 6.32) controlPoint1: CGPointMake(1.42, 8.57) controlPoint2: CGPointMake(2.4, 7.86)];
    [bezier56Path addLineToPoint: CGPointMake(2.4, -6.32)];
    [bezier56Path closePath];
    [bezier56Path moveToPoint: CGPointMake(0, 11.18)];
    [bezier56Path addCurveToPoint: CGPointMake(-6.22, 6.46) controlPoint1: CGPointMake(-3.82, 11.18) controlPoint2: CGPointMake(-6.22, 9.44)];
    [bezier56Path addLineToPoint: CGPointMake(-6.22, -6.46)];
    [bezier56Path addCurveToPoint: CGPointMake(0, -11.18) controlPoint1: CGPointMake(-6.22, -9.44) controlPoint2: CGPointMake(-3.82, -11.18)];
    [bezier56Path addCurveToPoint: CGPointMake(6.22, -6.46) controlPoint1: CGPointMake(3.82, -11.18) controlPoint2: CGPointMake(6.22, -9.44)];
    [bezier56Path addLineToPoint: CGPointMake(6.22, 6.46)];
    [bezier56Path addCurveToPoint: CGPointMake(0, 11.18) controlPoint1: CGPointMake(6.22, 9.44) controlPoint2: CGPointMake(3.82, 11.18)];
    [bezier56Path closePath];
    [fillColor setFill];
    [bezier56Path fill];

    CGContextRestoreGState(context);


    //// Group 3
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.50578 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.54945 * CGRectGetHeight(frame2));

        CGContextBeginTransparencyLayer(context, NULL);

        //// Clip Clip 3
        UIBezierPath* clip3Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-18.4, -18.4, 36.8, 36.8)];
        [clip3Path addClip];


        //// Oval 5 Drawing
        UIBezierPath* oval5Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-18.4, -18.4, 36.8, 36.8)];
        [fillColor setFill];
        [oval5Path fill];


        CGContextEndTransparencyLayer(context);

        CGContextRestoreGState(context);
    }


    //// Group 2
    {
        CGContextSaveGState(context);
        CGContextTranslateCTM(context, CGRectGetMinX(frame2) + 0.50578 * CGRectGetWidth(frame2), CGRectGetMinY(frame2) + 0.54580 * CGRectGetHeight(frame2));
        CGContextRotateCTM(context, -(angle + 225.5) * M_PI / 180);

        CGContextBeginTransparencyLayer(context, NULL);

        //// Clip Clip 2
        UIBezierPath* clip2Path = [UIBezierPath bezierPath];
        [clip2Path moveToPoint: CGPointMake(-41.34, 10.39)];
        [clip2Path addLineToPoint: CGPointMake(139.1, 2.3)];
        [clip2Path addLineToPoint: CGPointMake(-41.93, -11.55)];
        [clip2Path addLineToPoint: CGPointMake(-41.34, 10.39)];
        [clip2Path closePath];
        [clip2Path addClip];


        //// Bezier 30 Drawing
        UIBezierPath* bezier30Path = [UIBezierPath bezierPath];
        [bezier30Path moveToPoint: CGPointMake(-41.34, 10.39)];
        [bezier30Path addLineToPoint: CGPointMake(139.1, 2.3)];
        [bezier30Path addLineToPoint: CGPointMake(-41.93, -11.55)];
        [bezier30Path addLineToPoint: CGPointMake(-41.34, 10.39)];
        [bezier30Path closePath];
        [fillColor setFill];
        [bezier30Path fill];


        CGContextEndTransparencyLayer(context);

        CGContextRestoreGState(context);
    }
}

@end
