//
//  RDStyleKit.h
//  RaceData
//
//  Created by Alaija on 01/02/16.
//  Copyright (c) 2016 RaceData. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@interface RDStyleKit : NSObject

// Drawing Methods
+ (void)drawDayModeSpeedometerWithFrame2: (CGRect)frame2 fillColor: (UIColor*)fillColor pressure: (CGFloat)pressure;

@end
